server:
  port: 8085

spring:
  application:
    name: profAI

---
spring:
  config:
    activate:
      on-profile: dev
groq:
  url: https://api.groq.com/openai/v1/chat/completions
  clientSecret: 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
  
